// Loader + types for the baked efficient-frontier dataset (public/ef-data.json).
// Generated by pipeline/ef_universe.py and refreshed nightly by the GitHub Action.

export interface EFTicker {
  symbol: string
  name: string
  mean_annual: number
  vol_annual: number
}

export interface EFData {
  as_of: string
  years: number
  trading_days: number
  dates: string[]
  tickers: EFTicker[]
  returns: Record<string, number[]> // aligned daily log returns
}

export const EF_PRESETS: { label: string; tickers: string[] }[] = [
  { label: 'Big Tech', tickers: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META'] },
  {
    label: 'S&P Sectors',
    tickers: ['XLK', 'XLF', 'XLV', 'XLE', 'XLY', 'XLP', 'XLI', 'XLB', 'XLU', 'XLRE', 'XLC'],
  },
  { label: 'Global Mix', tickers: ['SPY', 'QQQ', 'IWM', 'EFA', 'EEM', 'TLT', 'GLD'] },
  { label: 'Growth', tickers: ['AAPL', 'MSFT', 'NVDA', 'TSLA', 'AMD', 'AVGO', 'CRM'] },
]

export async function loadEFData(): Promise<EFData> {
  const res = await fetch('/ef-data.json', { cache: 'force-cache' })
  if (!res.ok) throw new Error('Could not load market dataset.')
  return res.json()
}
